
//generated by tool, do not modify it
#include "Footer.h"

Footer::Footer()
:m_pControl1(NULL)
,m_pControl2(NULL)
,m_pControl3(NULL)
,m_pControl4(NULL)
,m_pControl5(NULL)
,m_pControl6(NULL)
,m_pControl7(NULL)
{

}

Footer::~Footer()
{
   
   CC_SAFE_RELEASE(m_pControl1);
   
   CC_SAFE_RELEASE(m_pControl2);
   
   CC_SAFE_RELEASE(m_pControl3);
   
   CC_SAFE_RELEASE(m_pControl4);
   
   CC_SAFE_RELEASE(m_pControl5);
   
   CC_SAFE_RELEASE(m_pControl6);
   
   CC_SAFE_RELEASE(m_pControl7);
   
}

bool Footer::init()
{
   setContentSize(CCSizeMake(640, 80));
   
  	setControl1(CCSprite::create("footer_bg_01.png"));
	m_pControl1->setAnchorPoint(CCPointZero);
	m_pControl1->setPosition(ccp(0,0));
	addChild(m_pControl1, 1);

   
  	setControl2(CCControlButton::create(CCLabelTTF::create("商城","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_6.png")));
	m_pControl2->setAnchorPoint(CCPointZero);
	m_pControl2->setPosition(ccp(534,0));
	m_pControl2->setAdjustBackgroundImage(false);
	m_pControl2->setZoomOnTouchDown(false);
	m_pControl2->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_6_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl2, 2);

   
  	setControl3(CCControlButton::create(CCLabelTTF::create("首页","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_1.png")));
	m_pControl3->setAnchorPoint(CCPointZero);
	m_pControl3->setPosition(ccp(0,0));
	m_pControl3->setAdjustBackgroundImage(false);
	m_pControl3->setZoomOnTouchDown(false);
	m_pControl3->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_1_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl3, 2);

   
  	setControl4(CCControlButton::create(CCLabelTTF::create("任务","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_2.png")));
	m_pControl4->setAnchorPoint(CCPointZero);
	m_pControl4->setPosition(ccp(106,0));
	m_pControl4->setAdjustBackgroundImage(false);
	m_pControl4->setZoomOnTouchDown(false);
	m_pControl4->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_2_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl4, 2);

   
  	setControl5(CCControlButton::create(CCLabelTTF::create("夺宝","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_3.png")));
	m_pControl5->setAnchorPoint(CCPointZero);
	m_pControl5->setPosition(ccp(213,0));
	m_pControl5->setAdjustBackgroundImage(false);
	m_pControl5->setZoomOnTouchDown(false);
	m_pControl5->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_3_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl5, 2);

   
  	setControl6(CCControlButton::create(CCLabelTTF::create("征讨","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_4.png")));
	m_pControl6->setAnchorPoint(CCPointZero);
	m_pControl6->setPosition(ccp(320,0));
	m_pControl6->setAdjustBackgroundImage(false);
	m_pControl6->setZoomOnTouchDown(false);
	m_pControl6->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_4_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl6, 2);

   
  	setControl7(CCControlButton::create(CCLabelTTF::create("阵容","Courier-Bold", 20), CCScale9Sprite::create("btn_menu_item_5.png")));
	m_pControl7->setAnchorPoint(CCPointZero);
	m_pControl7->setPosition(ccp(427,0));
	m_pControl7->setAdjustBackgroundImage(false);
	m_pControl7->setZoomOnTouchDown(false);
	m_pControl7->setBackgroundSpriteForState(CCScale9Sprite::create("btn_menu_item_5_selected.png"), CCControlStateHighlighted);
	addChild(m_pControl7, 2);

  


   return true;
}



